/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_sensetime_felix_FaceSDK */

#ifndef _Included_cn_sensetime_felix_FaceSDK
#define _Included_cn_sensetime_felix_FaceSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_sensetime_felix_FaceSDK
 * Method:    doInitResource
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_cn_sensetime_felix_FaceSDK_doInitResource
  (JNIEnv *, jobject, jstring);

/*
 * Class:     cn_sensetime_felix_FaceSDK
 * Method:    doDetect
 * Signature: ([BII)[I
 */
JNIEXPORT jintArray JNICALL Java_cn_sensetime_felix_FaceSDK_doDetect
  (JNIEnv *, jobject, jbyteArray, jint, jint);

/*
 * Class:     cn_sensetime_felix_FaceSDK
 * Method:    doExtract
 * Signature: ([BII[I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_cn_sensetime_felix_FaceSDK_doExtract
  (JNIEnv *, jobject, jbyteArray, jint, jint, jintArray);

/*
 * Class:     cn_sensetime_felix_FaceSDK
 * Method:    doVerify
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_cn_sensetime_felix_FaceSDK_doVerify
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     cn_sensetime_felix_FaceSDK
 * Method:    doDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_sensetime_felix_FaceSDK_doDestroy
  (JNIEnv *, jobject);


/*
* Class:     cn_sensetime_felix_FaceSDK
* Method:    doMultiTracker
* Signature: ([BII)[I
*/
JNIEXPORT jintArray JNICALL Java_cn_sensetime_felix_FaceSDK_doMultiTracker
(JNIEnv *env, jobject thiz, jbyteArray data, jint orientation, jint width, jint height);

/*
* Class:     cn_sensetime_felix_FaceSDK
* Method:    doMultiTrackerAlgin
* Signature: ([BII)[I
*/
JNIEXPORT jfloatArray JNICALL Java_cn_sensetime_felix_FaceSDK_doTrackerAlgin
(JNIEnv *env, jobject thiz, jintArray faceRectid);

/*
* Class:     cn_sensetime_felix_FaceSDK
* Method:    doGetPose
* Signature: ([BII)[I
*/
JNIEXPORT jfloatArray JNICALL Java_cn_sensetime_felix_FaceSDK_doGetPose
(JNIEnv *env, jobject thiz, jfloatArray facial_points_array);

#ifdef __cplusplus
}
#endif
#endif
